fix: end inference processes on certain fatal errors
Of note, certain cuda errors such as:
```
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

will now cause the process to end as the sub-process is in an unrecoverable state.